// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The agent's last self-reported verdict (via the `set_state` MCP tool).
 */
export type AgentReport = "working" | "idle";
