// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChromaMode } from "./ChromaMode";
import type { ClaudeConfig } from "./ClaudeConfig";
import type { CloneGroup } from "./CloneGroup";
import type { CodexConfig } from "./CodexConfig";
import type { DockerConfig } from "./DockerConfig";
import type { JudgeConfig } from "./JudgeConfig";
import type { LayoutPreset } from "./LayoutPreset";
import type { ListenConfig } from "./ListenConfig";
import type { PresetRedacted } from "./PresetRedacted";
import type { SshConfig } from "./SshConfig";

/**
 * The shape `GET /api/config` returns: the same structure as [`AppConfig`], each preset's
 * Linear key included verbatim, because the browser needs a key to query Linear with. For
 * those keys the redaction is a direction rather than a mask, and `PUT /api/config` takes
 * each one as write-only. Powers the Settings UI.
 *
 * Nothing in it is withheld. Every credential the server holds is either a preset's Linear
 * key, which the browser needs, or an account token that lives in its own store rather than
 * in the config.
 */
export type AppConfigRedacted = { listen: ListenConfig, agentPort: number, dataDir: string, staticDir: string, cloneSocket: string, setupComplete: boolean, layoutPresets: Array<LayoutPreset>, activeLayout: string, docker: DockerConfig, claude: ClaudeConfig, codex: CodexConfig, cloneGroups: Array<CloneGroup>, codexGroups: Array<CloneGroup>, presets: Array<PresetRedacted>, chroma: ChromaMode, ssh: SshConfig, agentPlaybook: string, globalPrompt: string, 
/**
 * Which GPT the stuck detector asks, and which Codex account pays for it.
 */
judge: JudgeConfig, };
