// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChromaMode } from "./ChromaMode";
import type { ClaudeConfig } from "./ClaudeConfig";
import type { CloneGroup } from "./CloneGroup";
import type { CodexConfig } from "./CodexConfig";
import type { DockerConfig } from "./DockerConfig";
import type { LayoutPreset } from "./LayoutPreset";
import type { ListenConfig } from "./ListenConfig";
import type { PresetRedacted } from "./PresetRedacted";
import type { SshConfig } from "./SshConfig";

/**
 * The shape `GET /api/config` returns: the same structure as [`AppConfig`], each preset's
 * Linear key included verbatim, because the browser needs a key to query Linear with. For
 * those keys the redaction is a direction rather than a mask, and `PUT /api/config` takes
 * each one as write-only. Powers the Settings UI.
 *
 * One field is genuinely withheld: the OpenRouter key, which arrives only as
 * [`Self::openrouter_key_set`]. Nothing in the browser calls OpenRouter, so there is no
 * reason to hand it over.
 */
export type AppConfigRedacted = { listen: ListenConfig, agentPort: number, dataDir: string, staticDir: string, cloneSocket: string, setupComplete: boolean, layoutPresets: Array<LayoutPreset>, activeLayout: string, docker: DockerConfig, claude: ClaudeConfig, codex: CodexConfig, cloneGroups: Array<CloneGroup>, codexGroups: Array<CloneGroup>, presets: Array<PresetRedacted>, chroma: ChromaMode, ssh: SshConfig, agentPlaybook: string, globalPrompt: string, 
/**
 * Which model answers the stuck question. Not a secret, so it passes through.
 */
openrouterModel: string, 
/**
 * Whether an OpenRouter key is stored. The key itself never leaves the server; this
 * is the whole test the settings panel runs to decide whether its write-only input
 * reads as already set.
 */
openrouterKeySet: boolean, };
