// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The chat panel's assistant: a pi-web server that RMNG talks to over its HTTP API. Each clone
 * gets one chat there, created on its first message. Both fields are plain addresses, so they
 * pass through redaction verbatim. An empty `url` means no assistant: the chat panel refuses to
 * send and says so.
 */
export type AssistantConfig = { 
/**
 * The pi-web origin, e.g. `http://10.0.0.12:9999`.
 */
url: string, 
/**
 * This RMNG's web API origin as the assistant reaches it, e.g. `http://10.0.0.129:9000`.
 * Written into each new chat's first message, so the assistant knows which server to pass
 * to `rmng --server`. The control-server cannot work this out itself: it runs on a Docker
 * bridge and does not know the address other machines use for it.
 */
serverUrl: string, };
