// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bidirectional audio for the port-1 viewer stream.
 *
 * Two independent switches: an operator may want to hear a clone without opening a
 * microphone into it, or run a fleet where mic injection is off entirely. Only the
 * **selected** clone ever streams, mirroring video — so this is fleet-wide, like
 * [`ChromaMode`], rather than per-clone.
 *
 * Audio is Opus at both endpoints; the control-server relays frames without decoding.
 */
export type AudioConfig = { 
/**
 * Stream the selected clone's desktop audio down to connected viewers.
 */
enabled: boolean, 
/**
 * Allow viewers to feed their microphone into the selected clone's virtual mic node.
 * This is the fleet-wide kill switch for a real privacy surface — with it on, a
 * connected viewer's microphone is live to whatever runs in the selected clone.
 */
micEnabled: boolean, };
