// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column of the dashboard board, holding clone ids top to bottom.
 *
 * Two things are deliberately absent. The archived column is not stored: its contents come
 * from [`RmngClone::archived`], so the two can never disagree. And a clone the operator has
 * not filed anywhere is not stored either: the board draws it in the first column, which is
 * how a newly created clone shows up without anyone writing it here first.
 *
 * Ids of clones that no longer exist are harmless — the board ignores them, and the next
 * move rewrites the column without them.
 */
export type BoardColumn = { id: string, title: string, cloneIds: Array<string>, };
