// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type Chat = { 
/**
 * The clone's chat on the assistant (a pi-web session id). `None` until the first
 * message creates it. The assistant owns the conversation itself.
 */
sessionId: string | null, 
/**
 * Lines RMNG wrote into the thread itself, never sent to the assistant: an expired
 * scheduled message, or a send that could not reach the assistant. The panel shows
 * them between the assistant's messages by time.
 */
notices: Array<ChatMessage>, };
