// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClaudeSpend = { usedCents: bigint, limitCents: bigint | null, pct: number, currency: string, resetsAt: string | null, };
