// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 0–100 utilization for a rolling usage window + when it resets.
 */
export type ClaudeUsageWindow = { pct: number, 
/**
 * ISO timestamp when the window resets, or null if unknown.
 */
resetsAt: string | null, };
