// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeSpend } from "./ClaudeSpend";
import type { ClaudeUsageWindow } from "./ClaudeUsageWindow";
import type { Provider } from "./Provider";

/**
 * A non-secret per-account usage view (tokens never enter this struct).
 */
export type ClaudeUsage = { 
/**
 * Stable, unique id: `${group}|${provider}|${email}` (group- and provider-scoped, since
 * one email can be authenticated into several groups and, within a group, under more than
 * one provider). Used only as an opaque key — never parsed positionally.
 */
id: string, email: string, provider: Provider | null, active: boolean, 
/**
 * Whether the account can run a clone right now: true while the token the server
 * holds for it has not expired, false once a broken refresh chain has outlived the
 * last token it minted. The rotator hands clones only to assignable accounts, so an
 * account that goes false is one the fleet moves off by itself. A failed usage poll
 * alone does not change it (see `stale`/`error` for that).
 */
assignable: boolean | null, error: string | null, stale: boolean | null, lastUpdated: bigint, fiveHour: ClaudeUsageWindow | null, sevenDay: ClaudeUsageWindow | null, 
/**
 * Claude only: the model-scoped weekly limit for the Fable model family. Purely
 * informational — it never gates account rotation (see the rotator, which keys off
 * `five_hour`/`seven_day` only). `None` for Codex and when the account has no such
 * scoped limit.
 */
fable: ClaudeUsageWindow | null, spend: ClaudeSpend | null, 
/**
 * Codex only: banked rate-limit reset credits ("usage resets") left on the
 * account. `None` for Claude (no such concept) and when usage is unavailable.
 */
resetCredits: bigint | null, };
