// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClaudeConfig = { 
/**
 * Usage poll interval (seconds, floored at 15).
 */
pollSecs: bigint, 
/**
 * Account email pinned to the top of the usage list.
 */
pinnedEmail: string | null, 
/**
 * Host id whose mounted home holds claude-swap's data dir (the template).
 */
templateHostId: string, 
/**
 * claude-swap data dir relative to the host's home.
 */
swapDataSubpath: string, 
/**
 * Hot-swap a clone to another account when its usage is exhausted.
 */
autoSwapOnExhaustion: boolean, };
