// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * No knobs left (usage poll interval + pinned email are hardcoded/gone). The struct
 * stays so the `claude` key in old config files keeps parsing.
 */
export type ClaudeConfig = Record<string, never>;
