// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Safe accumulated new-token totals for one clone, delivered in the named `tokens` SSE
 * event as a `{ hostId: CloneTokenUsage }` map. The server retains the activity timestamp
 * privately; it is deliberately absent here so clients cannot derive a clone status.
 */
export type CloneTokenUsage = {
/**
 * Input tokens newly processed by the model. Cache reads are excluded; native Anthropic
 * cache-creation tokens are included because they are newly processed.
 */
newInputTokens: bigint,
/**
 * Newly generated output tokens. Provider-specific reasoning is included exactly once
 * when its client-facing total does not already include it.
 */
outputTokens: bigint,
/**
 * Number of responses that reported a recognized final usage object.
 */
requestCount: bigint,
/**
 * True when this clone was served by the Fable model within the last 5 minutes. Derived
 * server-side from a private timestamp (never sent) and re-projected on a timer so it
 * decays back to false; drives the sidebar's "fable" badge next to the group binding.
 */
fableActive: boolean, };
