// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Safe accumulated new-token totals for one clone, delivered in the named `tokens` SSE
 * event as a `{ hostId: CloneTokenUsage }` map. The server retains the activity timestamp
 * privately; it is deliberately absent here so clients cannot derive a clone status.
 */
export type CloneTokenUsage = {
/**
 * Input tokens newly processed by the model. Cache reads are excluded; native Anthropic
 * cache-creation tokens are included because they are newly processed.
 */
newInputTokens: bigint,
/**
 * Newly generated output tokens. Provider-specific reasoning is included exactly once
 * when its client-facing total does not already include it.
 */
outputTokens: bigint,
/**
 * Number of responses that reported a recognized final usage object.
 */
requestCount: bigint, };
