// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorState } from "./MonitorState";
import type { PortForward } from "./PortForward";

export type Clone = { 
/**
 * Stable id; equals the Docker container name for a managed clone.
 */
id: string, 
/**
 * Endpoint hostname/IP for unmanaged rows. Display-only on managed clones (it
 * records the container name == `id`; dials resolve via Docker DNS / inspect).
 */
host: string, 
/**
 * Port (defaults to 3389 for the legacy RDP path).
 */
port: number, username: string, password: string, domain: string | null, gdm_username: string | null, gdm_password: string | null, 
/**
 * True for a managed clone: a Docker container whose *name equals this clone's id*
 * backs it (every Docker call addresses it by that name — no stored container id).
 * False is a plain unmanaged row (legacy/hand-added, deletable in the UI). Old
 * `state.json` rows carrying the retired `ctid`/`container` keys load as
 * unmanaged — serde drops the stale keys.
 */
managed: boolean, 
/**
 * True when this managed clone is intentionally stopped but retained. Its container,
 * named volumes, notes, and chat history remain available for a later unarchive.
 */
archived: boolean, source: string | null, 
/**
 * Email of the imported Claude account whose access token is written into this clone's
 * `~/.claude/.credentials.json`. The control-server owns the refresh lifecycle and
 * re-pushes on every rotation; the clone never holds a refresh token.
 */
claudeAccountEmail: string | null, 
/**
 * Name of the Claude group this clone is balanced within (sticky — it moves only
 * when its account exhausts); `None` when bound to a single fixed account. When
 * set, `claude_account_email` holds the current pick.
 */
claudeGroup: string | null, 
/**
 * The operator's Claude *selection*: `"auto"` or an account email (a pin — any
 * imported account, even outside the clone's group). Distinguishes an auto-managed
 * clone (server picks the best account in scope and may hot-swap it) from one pinned
 * to a fixed account — `claude_account_email` alone can't tell these apart. Group
 * binding moved to the shared [`RmngClone::group`]: with a group set, an `"auto"`
 * selection resolves inside it, otherwise fleet-wide. Legacy `"none"`/`"group:<name>"`
 * values migrate to `"auto"` (+ `group`) on load.
 */
claudeSelection: string | null, 
/**
 * Email of the imported Codex (ChatGPT) account whose token is written into this
 * clone's `~/.codex/auth.json`. Independent of `claude_account_email` — a clone can
 * hold both. `None` when no Codex account is assigned.
 */
codexAccountEmail: string | null, 
/**
 * Name of the Codex group this clone is balanced within (sticky, like `claude_group`);
 * `None` when bound to a single fixed Codex account.
 */
codexGroup: string | null, 
/**
 * The operator's Codex *selection*: `"auto"` or an account email (a pin) — the
 * Codex twin of `claude_selection`. Group binding is shared (see [`RmngClone::group`]).
 */
codexSelection: string | null, 
/**
 * Name of the single account pool this clone draws BOTH providers' accounts from
 * (`None` = no pool). With a group set, an `"auto"` per-side selection resolves to
 * the least-used member of that side's provider inside the group; an explicit email
 * or `"none"` on a side overrides the group for that side only. `claude_group` /
 * `codex_group` record the group each side's current account was picked from.
 */
group: string | null, 
/**
 * Lowercase Linear workspace name / ticket prefix (e.g. `"we"`). An open
 * string: the workspace set is config (Settings → Linear API keys), not an enum.
 */
linearWorkspace: string | null, linearTicket: string | null, linearTicketUrl: string | null, linearBranch: string | null, 
/**
 * Clone preset name used at creation. New control-server versions persist this so
 * reconciliation can rebuild `/etc/environment` without relying on a guest-side
 * legacy env file. Older clones may not have it.
 */
presetName: string | null, displayName: string | null, linearLabel: string | null, 
/**
 * Current server-owned lifecycle state. Derived from Docker liveness plus the clone's own
 * Claude Code session registry and agent hooks, never reported by a clone-local process.
 */
monitorState: MonitorState | null, 
/**
 * Whether `monitor_state` is a reading at all, or only the absence of one.
 *
 * Set when the judge that decides `working` could not be reached and the files could not
 * settle the clone on their own. `monitor_state` reads `idle` alongside it, which is what
 * an older client showed in that situation anyway — so a client that does not know this
 * field is exactly as right as it was before, and one that does can say "no reading"
 * instead of asserting the agent stopped. A clone flagged here may well be working.
 */
activityUnknown: boolean, 
/**
 * The clone container's IPv4 on the rmng bridge network — the address other
 * clones can dial it at directly (alongside its `id`, which Docker's embedded
 * DNS resolves to the same clone). Populated by the monitor poller from a Docker
 * inspect each tick; `None` for unmanaged rows or a stopped/detached container.
 * A recreated container's new IP self-heals on the next poll.
 */
localIp: string | null, 
/**
 * Set when a clone transitions from `working` to `idle`/`offline` while it is not selected.
 * Clearing the selection state is an explicit operator action, not a clone report.
 */
unread: boolean, 
/**
 * A headless clone has **no desktop**: its display (`gnome-headless.service`) and capture
 * daemon (`rmng-clone-daemon.service`) are disabled at create time, so it streams no video.
 * Selecting it drives the viewer's tmux tab view instead of an H.264 desktop stream (see
 * the control-server `termplane`). Created from the same template as a regular clone.
 */
headless: boolean, 
/**
 * The id of this clone's parent, when it is a sub clone. One level deep only — a clone
 * that has a parent is never itself a parent. `None` = top-level. Purely cosmetic
 * grouping in the sidebar and `rmng clone ls`; a sub clone is otherwise an ordinary managed
 * clone (its own group binding, router key, tokens, and video). Cascade-deleted with
 * its parent.
 */
parent: string | null, 
/**
 * Local port-forward rules for this clone (see [`PortForward`]). Persisted; the
 * viewer runs the listeners and reports status out-of-band (volatile `forwards`
 * SSE event, never stored here).
 */
forwards: Array<PortForward>, 
/**
 * Gen-2 home dataset name, e.g. `tank/rmng/homes/<id>`. `None` on pre-gen-2 rows
 * (serde-defaulted so old `state.json` loads); the dataset bind mount on the
 * container marks a gen-2 clone, no separate gen label is kept.
 */
dataset: string | null, 
/**
 * Derived image tag this clone was created from (`rmng-p-<hash>`). Recorded so
 * fork and rebase resolve the same base, and delete can purge the tag when no
 * remaining clone references it.
 */
baseTag: string | null, 
/**
 * Whether the clone-daemon currently holds its media-socket session. Volatile:
 * overlaid at `/api/state` serve time from the live connection table, never
 * a persisted fact (a `state.json` copy may hold a stale value). Headless and
 * archived clones read false — no daemon runs there to connect.
 */
daemonConnected: boolean, };
