// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorState } from "./MonitorState";
import type { PortForward } from "./PortForward";

export type Clone = { 
/**
 * Stable id; equals the Docker container name for a managed clone.
 */
id: string, 
/**
 * Endpoint hostname/IP for unmanaged rows. Display-only on managed clones (it
 * records the container name == `id`; dials resolve via Docker DNS / inspect).
 */
host: string, 
/**
 * Port (defaults to 3389 for the legacy RDP path).
 */
port: number, username: string, password: string, domain: string | null, gdm_username: string | null, gdm_password: string | null, 
/**
 * True for a managed clone: a Docker container whose *name equals this clone's id*
 * backs it (every Docker call addresses it by that name — no stored container id).
 * False is a plain unmanaged row (legacy/hand-added, deletable in the UI). Old
 * `state.json` rows carrying the retired `ctid`/`container` keys load as
 * unmanaged — serde drops the stale keys.
 */
managed: boolean, 
/**
 * True when this managed clone is intentionally stopped but retained. Its container,
 * named volumes, notes, and chat history remain available for a later unarchive.
 */
archived: boolean, source: string | null, 
/**
 * Email of the imported Claude account whose access token is written into this clone's
 * `~/.claude/.credentials.json`. The control-server owns the refresh lifecycle and
 * re-pushes on every rotation; the clone never holds a refresh token.
 */
claudeAccountEmail: string | null, 
/**
 * Name of the Claude group this clone is balanced within (sticky — it moves only
 * when its account exhausts); `None` when bound to a single fixed account. When
 * set, `claude_account_email` holds the current pick.
 */
claudeGroup: string | null, 
/**
 * The operator's Claude *selection* verbatim: `"auto"`, `"none"`, `"group:<name>"`,
 * or an account email. Distinguishes an auto-managed clone (server picks the best
 * account and may hot-swap it) from one pinned to a fixed account or opted out of
 * a token entirely — `claude_account_email` alone can't tell these apart. `None` on
 * clones created before this field / when no Claude account is configured.
 */
claudeSelection: string | null, 
/**
 * Email of the imported Codex (ChatGPT) account whose token is written into this
 * clone's `~/.codex/auth.json`. Independent of `claude_account_email` — a clone can
 * hold both. `None` when no Codex account is assigned.
 */
codexAccountEmail: string | null, 
/**
 * Name of the Codex group this clone is balanced within (sticky, like `claude_group`);
 * `None` when bound to a single fixed Codex account.
 */
codexGroup: string | null, 
/**
 * The operator's Codex *selection* verbatim: `"auto"`, `"none"`, `"group:<name>"`, or
 * an account email — the Codex twin of `claude_selection`.
 */
codexSelection: string | null, 
/**
 * Lowercase Linear workspace name / ticket prefix (e.g. `"we"`). An open
 * string: the workspace set is config (Settings → Linear API keys), not an enum.
 */
linearWorkspace: string | null, linearTicket: string | null, linearTicketUrl: string | null, linearBranch: string | null, 
/**
 * Clone preset name used at creation. New control-server versions persist this so
 * reconciliation can rebuild `/etc/environment` without relying on a guest-side
 * legacy env file. Older clones may not have it.
 */
presetName: string | null, displayName: string | null, linearLabel: string | null, 
/**
 * Current server-owned lifecycle state. It is derived from Docker liveness and passive
 * proxy token activity, never reported by a clone-local process.
 */
monitorState: MonitorState | null, 
/**
 * The clone container's IPv4 on the rmng bridge network — the address other
 * clones can dial it at directly (alongside its `id`, which Docker's embedded
 * DNS resolves to the same clone). Populated by the monitor poller from a Docker
 * inspect each tick; `None` for unmanaged rows or a stopped/detached container.
 * A recreated container's new IP self-heals on the next poll.
 */
localIp: string | null, 
/**
 * Set when a clone transitions from `working` to `idle`/`offline` while it is not selected.
 * Clearing the selection state is an explicit operator action, not a clone report.
 */
unread: boolean, 
/**
 * A headless clone has **no desktop**: its display (`gnome-headless.service`) and capture
 * daemon (`rmng-clone-daemon.service`) are disabled at create time, so it streams no video.
 * Selecting it drives the viewer's tmux tab view instead of an H.264 desktop stream (see
 * the control-server `termplane`). Created from the same template as a regular clone.
 */
headless: boolean, 
/**
 * The id of this clone's parent, when it is a sub clone. One level deep only — a clone
 * that has a parent is never itself a parent. `None` = top-level. Purely cosmetic
 * grouping in the sidebar and `rmng clone ls`; a sub clone is otherwise an ordinary managed
 * clone (its own group binding, router key, tokens, and video). Cascade-deleted with
 * its parent.
 */
parent: string | null, 
/**
 * Local port-forward rules for this clone (see [`PortForward`]). Persisted; the
 * viewer runs the listeners and reports status out-of-band (volatile `forwards`
 * SSE event, never stored here).
 */
forwards: Array<PortForward>, };
