// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All-time token totals for one clone, summed across both providers.
 *
 * Accumulated from the agent CLIs' own session logs — the JSONL transcripts under
 * `~/.claude/projects` and `~/.codex/sessions` — which every agent writes regardless of
 * whether RMNG or a human at a shell launched it. Cumulative
 * since the clone was first scanned and persisted in `state.json`, because both CLIs prune
 * old session files — a figure re-derived from whatever logs still exist would silently
 * shrink as history ages out.
 *
 * Counts the *clone*, not the account: hot-swapping a clone's account leaves the total
 * climbing across the swap. It answers "which clone is expensive", not "what did this
 * account spend" — the per-account 5h/7d windows in [`ClaudeUsage`] answer the latter.
 */
export type CloneTokens = { 
/**
 * Newly processed input tokens. Cache *reads* are excluded — one sampled response had
 * 210,735 cache-read tokens against 1 real input token, so including them would swamp
 * the figure. Cache *creation* is included: those tokens really were processed.
 */
inputTokens: bigint, 
/**
 * Newly generated output tokens, including Codex reasoning tokens (its client-facing
 * `output_tokens` does not already include them).
 */
outputTokens: bigint, 
/**
 * True when this clone's most recent Claude response came from the Fable model family
 * within the last few minutes. Derived server-side from a private timestamp (never
 * sent) and re-projected each scan so it decays back to false; drives the sidebar
 * badge beside the Claude account.
 */
fableActive: boolean, };
