// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinearMeta } from "./LinearMeta";

/**
 * The body of `POST /api/clone` (a clone built from a preset image onto a fresh home) and
 * of `POST /api/fork` (a copy of a live clone's home). One type: the two requests differ
 * only in where the home comes from, which is the route.
 *
 * What an omitted field becomes is decided in one place, the control-server's `clone_plan`:
 * the preset, the pool and both accounts, and the clone's own name — which no client can
 * pick, because a free name needs the live clone list. `Default` leaves every flag off, so
 * a caller building one by hand states `run_startup_script` itself.
 */
export type CloneRequest = { 
/**
 * Fork only: the clone whose home is copied. Omitted, the preset's default fork clone
 * where it is still forkable, else the oldest forkable clone.
 */
source?: string, 
/**
 * Preset name: its Dockerfile builds the image and its vars are the clone's
 * environment. Required while any presets exist, except on a fork, which keeps its
 * source's preset when this is omitted.
 */
preset?: string, 
/**
 * The ticket this clone is for, `displayName` carrying its title. A clone built from a
 * preset image needs a title; a fork without this keeps its source's ticket.
 */
linear?: LinearMeta, 
/**
 * This side's account: an email pins it, `auto` rotates inside the pool, `none` leaves
 * the clone tokenless, and a legacy `group:<pool>` binds that pool. Omitted, a fork
 * keeps its source's account and every other clone takes `auto`.
 */
claudeAccount?: string, codexAccount?: string, 
/**
 * The pool both sides draw their accounts from: a name binds, `none` unbinds to every
 * pool. Omitted, the named preset's pool, else (on a fork) the source's.
 */
group?: string, 
/**
 * Sent to the agent as its first turn once the clone is up.
 */
firstMessage?: string, 
/**
 * Appended to the clone agent's and to Claude Code's default instructions.
 */
agentInstructions?: string, claudeInstructions?: string, 
/**
 * No desktop: the viewer shows a tmux tab view instead of a video stream.
 */
headless: boolean, 
/**
 * Run the preset's startup script as the clone user, as the last step of the build.
 */
runStartupScript: boolean, 
/**
 * Build the preset's image fresh, with a fresh base pull, even when its tag exists.
 */
rebuild: boolean, };
