// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded auto-consumed (or reserved) Codex reset. Persisted in `ControlState`
 * so a server restart can't re-spend on an account already reset this 7d window.
 */
export type CodexResetMark = { accountId: string, 
/**
 * The 7d window (its `resets_at` epoch **seconds**) this reset was spent against —
 * the cooldown key. An account is on cooldown while its current 7d window matches.
 */
windowResetsAt: bigint, 
/**
 * Wall-clock ms when the mark was reserved / consume attempted (audit / UI tooltip).
 */
consumedAt: bigint, 
/**
 * Idempotency key sent to `/consume` for this reservation (audit; enables a future
 * safe same-key retry — v1 does not retry within a window).
 */
redeemRequestId: string, };
