// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexConfig = { 
/**
 * When true, auto-spend one banked reset credit once every managed Codex account
 * is over the weekly cap with no 7d reset within 24h (see `codex.rs` fleet gate).
 */
autoReset: boolean, };
