// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clone } from "./Clone";
import type { CodexResetMark } from "./CodexResetMark";
import type { GroupUsage } from "./GroupUsage";
import type { MonitorSpec } from "./MonitorSpec";
import type { Operation } from "./Operation";

/**
 * The top-level state broadcast over `/events` and persisted to `state.json`.
 */
export type ControlState = { 
/**
 * Id of the clone that should be displayed. May be absent or point at a clone
 * not in the list; consumers must tolerate both.
 */
selected: string | null, monitors: Array<MonitorSpec>, 
/**
 * Name of the active layout preset (mirrored from config so the sidebar switcher
 * updates live over `/events`). Empty when no presets exist.
 */
activeLayout: string, 
/**
 * Names of all layout presets, in config order — the sidebar's segmented buttons.
 */
layoutPresetNames: Array<string>, hosts: Array<Clone>, operations: Array<Operation>, 
/**
 * Per-group usage view (no tokens) under the group-proxy model: for each account pool,
 * the accounts authenticated into its CLIProxyAPI instance's `auth-dir`, with 5h/7d/fable
 * windows. Refreshed by the by-group usage poller.
 */
usageGroups: Array<GroupUsage>, 
/**
 * Codex auto-reset bookkeeping (cooldown). Non-secret; changes at most once per
 * account per week, so it belongs in `state.json` (unlike per-tick stats).
 */
codexResetMarks: Array<CodexResetMark>, };
