// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live per-container resource usage, sampled by the monitor poller each tick and pushed
 * to the frontend as a named `stats` SSE event carrying a `{ hostId: ContainerStats }`
 * map. Deliberately NOT a field of [`ControlState`] / [`RmngClone`]: it changes every tick, so
 * routing it through the state store would rewrite `state.json` every few seconds (every
 * `ControlState` mutation persists — see the control-server's `state.rs`). It rides the
 * same `/events` stream on a separate SSE-only bus instead.
 */
export type ContainerStats = { 
/**
 * CPU use as a percentage of total host capacity (100 == every available core busy).
 */
cpuPct: number, 
/**
 * RAM usage excluding reclaimable page cache, plus swap usage, in bytes. Tmpfs and
 * shared-memory charges remain included.
 */
memUsed: bigint, 
/**
 * RAM plus swap limit in bytes; 0 when either cgroup limit is unbounded or unavailable.
 */
memLimit: bigint, };
