// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeUsage } from "./ClaudeUsage";
import type { Clone } from "./Clone";
import type { CloneTokens } from "./CloneTokens";
import type { CodexResetMark } from "./CodexResetMark";
import type { MonitorSpec } from "./MonitorSpec";
import type { Operation } from "./Operation";

/**
 * The top-level state broadcast over `/events` and persisted to `state.json`.
 */
export type ControlState = { 
/**
 * Id of the clone that should be displayed. May be absent or point at a clone
 * not in the list; consumers must tolerate both.
 */
selected: string | null, monitors: Array<MonitorSpec>, 
/**
 * Name of the active layout preset (mirrored from config so the sidebar switcher
 * updates live over `/events`). Empty when no presets exist.
 */
activeLayout: string, 
/**
 * Names of all layout presets, in config order — the sidebar's segmented buttons.
 */
layoutPresetNames: Array<string>, hosts: Array<Clone>, operations: Array<Operation>, 
/**
 * Per-account usage view (no tokens). Despite the name it holds **both** providers'
 * rows, distinguished by [`ClaudeUsage::provider`]; `clone_ops::replace_provider_views`
 * is what lets the Claude and Codex pollers publish here without clobbering each other.
 */
claudeAccounts: Array<ClaudeUsage>, 
/**
 * Codex auto-reset bookkeeping (cooldown). Non-secret; changes at most once per
 * account per week, so it belongs in `state.json` (unlike per-tick stats).
 */
codexResetMarks: Array<CodexResetMark>, 
/**
 * All-time per-clone token totals, keyed by clone id. Unlike the volatile CPU/RAM
 * stats map (which rides its own SSE bus precisely because it changes every tick),
 * this is persisted: it is cumulative, and the logs it is derived from get pruned.
 */
cloneTokens: { [key in string]?: CloneTokens }, };
