// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Docker backend settings for the clone fleet. No secrets — the local daemon is
 * reached over the unix socket, so (unlike the retired Proxmox SSH target) there is
 * nothing to redact; the whole struct passes through into [`AppConfigRedacted`].
 */
export type DockerConfig = { 
/**
 * Prefix for derived clone hostnames/names, e.g. `pega-` → `pega-dev-123`. Sanitized
 * to DNS-label-safe chars at use; blank in the UI keeps the stored value. Immediate
 * (carried from the retired `proxmox.hostname_prefix`).
 */
hostnamePrefix: string, 
/**
 * CPU limit per clone (`nano_cpus` = `clone_cpus * 1e9`), matching LXC parity.
 */
cloneCpus: number, 
/**
 * Memory limit per clone in MiB (+8 GiB swap), matching LXC parity.
 */
cloneMemoryMb: number, 
/**
 * REMOVED `profile_lines`: presets carry their own full Dockerfile now.
 * Template home seed snapshot (`<dataset>@<snap>`). A create clones the new home
 * from it by default, so template clones start with content; empty means a fresh
 * home. Seed refresh is manual.
 */
seedSnapshot: string | null, 
/**
 * Parent ZFS dataset for all gen-2 clone homes (`<this>/<clone-id>`), mounted
 * into the outer CT once at `/srv/rmng-homes`. Per-machine: the pool name differs
 * per host (e.g. `tank/rmng/homes` vs `rpool/rmng/homes`). Immediate-apply (read
 * fresh per zfs call); changing it does not move existing datasets.
 */
homesParent: string, };
