// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVar } from "./EnvVar";

/**
 * A named set of environment variables, applied to a clone's session when chosen at
 * clone time (written to `~/.config/environment.d/30-rmng-preset.conf`). Vars that must
 * ALWAYS be present (e.g. `XDG_CURRENT_DESKTOP`) are NOT presets — they're baked into the
 * template's base session env by `provision-clone.sh`, inherited by every clone.
 */
export type EnvPreset = { name: string, vars: Array<EnvVar>, };
