// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { Provider } from "./Provider";

/**
 * One member of an account pool: an email plus which provider it serves.
 * `provider` is absent for an untagged member, which serves both sides — that is
 * also how every pre-tag member deserializes (a bare `"a@x"` string reads as an
 * untagged member), so old configs keep working with unchanged behavior. Tagging
 * matters when one email names two accounts: a Claude account and a Codex
 * account can share an address, and without a tag one group entry claims both.
 */
export type GroupMember = { email: string, provider?: Provider | null, };
