// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `rmng-cliproxy` sidecar's status, served by `GET /api/groupproxy`.
 *
 * That container owns the `/cc` router + every per-group CLIProxyAPI process, and a
 * control-server update deliberately does NOT roll it forward — recreating it would drop every
 * in-flight agent turn in the fleet, which is precisely the interruption the split removes. So
 * the operator needs the drift to be *visible*: `behind` is true whenever it is running a
 * different image than the control-server, and `POST /api/groupproxy/restart` is the deliberate
 * roll-forward. `detail` is always populated (including for a down daemon), so the UI renders
 * something useful in every state.
 */
export type GroupProxyStatus = { 
/**
 * The container/DNS name (`rmng-cliproxy`).
 */
container: string, running: boolean, 
/**
 * Short image id it is running, when it exists.
 */
image: string | null, 
/**
 * `org.opencontainers.image.revision` of that image, when the image carries one (a plain
 * `docker build` leaves it empty — a dev build).
 */
revision: string | null, 
/**
 * It is running a different image than the control-server.
 */
behind: boolean, 
/**
 * Human-readable state for the Settings panel.
 */
detail: string, };
