// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeUsage } from "./ClaudeUsage";

/**
 * Per-group usage view: one account pool (a CLIProxyAPI instance) plus the accounts
 * authenticated into its `auth-dir`, each with its 5h/7d/fable windows. The by-group
 * replacement for the flat `claude_accounts` list — the same email can appear under
 * several groups (independent token sets per instance), so ids are group-scoped.
 */
export type GroupUsage = { name: string, accounts: Array<ClaudeUsage>, };
