// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named account pool backed by one CLIProxyAPI instance (see the group-proxy
 * redesign, `docs/superpowers/specs/2026-07-19-cliproxy-group-proxy-plan.md`). A pool is
 * provider-agnostic — it may hold Claude and/or GPT accounts, added by OAuth login into
 * that instance's `auth-dir`. A clone binds exactly one group; the control-server routes
 * every request from that clone's agents to the group's instance. Carries no secrets —
 * just a name — so it's TS-exported and shown verbatim in the redacted config. Membership
 * is NOT stored here; it's derived from the instance's `auth-dir` at runtime.
 */
export type Group = { name: string, };
