// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReport } from "./AgentReport";
import type { MonitorState } from "./MonitorState";
import type { PortForward } from "./PortForward";

export type Host = { 
/**
 * Stable id; equals the Docker container name for cloneable hosts.
 */
id: string, 
/**
 * Endpoint hostname/IP for unmanaged rows. Display-only on managed clones (it
 * records the container name == `id`; dials resolve via Docker DNS / inspect).
 */
host: string, 
/**
 * Port (defaults to 3389 for the legacy RDP path).
 */
port: number, username: string, password: string, domain: string | null, gdm_username: string | null, gdm_password: string | null, 
/**
 * True for a managed clone: a Docker container whose *name equals this host's id*
 * backs it (every Docker call addresses it by that name — no stored container id).
 * False is a plain unmanaged row (legacy/hand-added, deletable in the UI). Old
 * `state.json` rows carrying the retired `ctid`/`container` keys load as
 * unmanaged — serde drops the stale keys.
 */
managed: boolean,
/**
 * True when this managed clone is intentionally stopped but retained. Its container,
 * named volumes, notes, and chat history remain available for a later unarchive.
 */
archived: boolean, source: string | null,
/**
 * Group-proxy binding: the account pool (one CLIProxyAPI instance) this clone's agents
 * route through, via the control-server's `/cc` router. `None` = no inference. This is
 * the sole account binding — CLIProxyAPI owns intra-group account selection + refresh.
 */
group: string | null, 
/**
 * Lowercase Linear workspace name / ticket prefix (e.g. `"we"`). An open
 * string: the workspace set is config (Settings → Linear API keys), not an enum.
 */
linearWorkspace: string | null, linearTicket: string | null, linearTicketUrl: string | null, linearBranch: string | null, 
/**
 * Clone preset name used at creation. New control-server versions persist this so
 * reconciliation can rebuild `/etc/environment` without relying on a guest-side
 * legacy env file. Older hosts may not have it.
 */
presetName: string | null, displayName: string | null, linearLabel: string | null, agentReport: AgentReport | null, stateNote: string | null, monitorState: MonitorState | null, 
/**
 * The clone container's IPv4 on the rmng bridge network — the address other
 * clones can dial it at directly (alongside its `id`, which Docker's embedded
 * DNS resolves to the same host). Populated by the monitor poller from a Docker
 * inspect each tick; `None` for unmanaged rows or a stopped/detached container.
 * A recreated container's new IP self-heals on the next poll.
 */
localIp: string | null, 
/**
 * True when this clone fell out of `working` (→ idle/offline) since the
 * operator last viewed it — drives the sidebar "unread" dot. Set by the
 * monitor poller on that transition, cleared when the clone is activated.
 */
unread: boolean, 
/**
 * Local port-forward rules for this host (see [`PortForward`]). Persisted; the
 * viewer runs the listeners and reports status out-of-band (volatile `forwards`
 * SSE event, never stored here).
 */
forwards: Array<PortForward>, };
