// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReport } from "./AgentReport";
import type { LinearWorkspace } from "./LinearWorkspace";
import type { MonitorState } from "./MonitorState";

export type Host = { 
/**
 * Stable id; equals the Proxmox container hostname for cloneable hosts.
 */
id: string, 
/**
 * RDP/media server hostname or IP.
 */
host: string, 
/**
 * Port (defaults to 3389 for the legacy RDP path).
 */
port: number, username: string, password: string, domain: string | null, gdm_username: string | null, gdm_password: string | null, ctid: number | null, source: string | null, claudeAccountEmail: string | null, linearWorkspace: LinearWorkspace | null, linearTicket: string | null, linearTicketUrl: string | null, linearBranch: string | null, displayName: string | null, linearLabel: string | null, agentReport: AgentReport | null, stateNote: string | null, monitorState: MonitorState | null, };
