// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which backend settles the clones the file checks cannot.
 *
 * `codex` asks GPT on the best imported Codex account's ChatGPT plan.
 * `gemini` asks Gemini with the stored API key.
 */
export type JudgeProvider = "codex" | "gemini";
