// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JudgeProvider } from "./JudgeProvider";

/**
 * What settles the clones the file checks cannot.
 *
 * Two backends. `codex` bills the best imported Codex account. `gemini` uses the stored
 * API key. The key passes through redaction verbatim, like preset Linear keys.
 */
export type JudgeConfig = { provider: JudgeProvider, 
/**
 * Gemini API key, verbatim. Empty means unset.
 */
geminiKey: string, };
