// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What settles the clones the file checks cannot: GPT, on an imported Codex account's
 * ChatGPT plan. See [`crate::MonitorState`].
 *
 * No credential of its own. The server already holds that account's OAuth pair to run the
 * clones, and the judge spends the same weekly allowance they do. With no Codex account
 * imported, nothing answers the question and no clone is ever reported as working. That is
 * deliberate: a guess in either direction is worse than an honest "not working", and
 * per-clone token accounting is unaffected either way.
 *
 * Nothing here is secret, so the whole struct reaches the browser.
 */
export type JudgeConfig = { 
/**
 * Which GPT answers.
 */
codexModel: string, 
/**
 * Which imported Codex account pays for those calls. Unset means the first imported
 * account, so a rig with one account needs no answer here. The calls come out of that
 * account's weekly ChatGPT allowance, the same one its clones spend.
 *
 * `Option` for the same reason [`ClaudeConfig::pinned_email`] is one: a `PUT` reads an
 * empty string as "keep what is stored", so `null` is how the panel says "no account in
 * particular" once one has been picked.
 */
codexEmail: string | null, };
