// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Linear workspace as shown to the browser: its name + whether a key is stored.
 */
export type LinearKeyRedacted = { name: string, set: boolean, };
