// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketLabel } from "./TicketLabel";
import type { TicketLink } from "./TicketLink";
import type { TicketState } from "./TicketState";

/**
 * A Linear issue assigned to the owner of one of the configured preset API keys.
 *
 * Each key is personal and answers only for its own owner, so the poller queries every
 * configured key and publishes the union. Nothing here says which key found a ticket: the
 * operator holds all of them, and the answer would never change what they do next.
 */
export type LinearTicket = { 
/**
 * Human identifier, e.g. `WE-142`. Also what the clone dialog parses.
 */
id: string, title: string, 
/**
 * Canonical Linear URL, which is what a drop hands the clone dialog.
 */
url: string, state: TicketState, 
/**
 * Team key, e.g. `WE`. It is what picks the preset, so it is worth showing.
 */
team?: string, 
/**
 * Linear's priority, 1 (urgent) to 4 (low). Absent when none is set.
 */
priority?: number, 
/**
 * Always serialized, empty list included: the column maps over it unconditionally,
 * and an absent array would make every consumer guard a field that is never unknown.
 */
labels: Array<TicketLabel>, 
/**
 * Linear's own `branchName`, which is the string its "copy git branch name" produces.
 */
branchName?: string, 
/**
 * The issue body, as Linear stores it: markdown. Absent when the issue has none.
 */
description?: string, 
/**
 * Display name of whoever it is assigned to. Every ticket here is assigned to one of
 * the operator's own accounts, so the cards leave it off — the detail panel shows it
 * because a fleet with several keys has several owners.
 */
assignee?: string, 
/**
 * `YYYY-MM-DD`, as Linear sends it.
 */
dueDate?: string, 
/**
 * Linear's point estimate, whatever scale the team set.
 */
estimate?: number, 
/**
 * The issue this one hangs under, when it is itself a sub-issue.
 */
parent?: TicketLink, 
/**
 * Sub-issues, in Linear's order, whatever state they are in. Always serialized so the
 * panel can map over it without guarding a field that is never unknown.
 */
children: Array<TicketLink>, };
