// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Linear ticket a clone was made for: what its row stores, what the board draws, and
 * what the agent is started on. `display_name` is the clone's title — the issue's own for a
 * ticket clone, whatever was typed for one without.
 */
export type LinearMeta = { 
/**
 * Lowercase workspace / ticket prefix, e.g. `we`.
 */
workspace?: string, 
/**
 * Ticket identifier, e.g. `WE-142`. Names the clone when present.
 */
ticket?: string, ticketUrl?: string, 
/**
 * Linear's own `branchName`.
 */
branch?: string, 
/**
 * The clone's title.
 */
displayName?: string, 
/**
 * The issue's first label, which is the only one a clone carries.
 */
label?: string, };
