// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live resource usage for the entire CT 105 LXC that hosts RMNG. Published as the volatile
 * `lxcStats` SSE event, separately from per-clone [`ContainerStats`] rows, so control-server,
 * Docker, registry, cache, and unmanaged CT work are included without entering `state.json`.
 */
export type LxcStats = { 
/**
 * CT-wide CPU use; 100 means CT 105's enforced 16-CPU capacity was busy. `None` is
 * emitted until two cgroup samples establish a rate.
 */
cpuPct: number | null, 
/**
 * RAM usage excluding reclaimable page cache, plus swap usage, in bytes. Tmpfs and
 * shared-memory charges remain included.
 */
memUsed: bigint, 
/**
 * RAM plus swap limit in bytes; 0 when either cgroup limit is unbounded or unavailable.
 */
memLimit: bigint, 
/**
 * Physical, compression-aware use of CT 105's ZFS root filesystem, in bytes.
 */
diskUsed: bigint | null, };
