// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One monitor in the global desired layout: size, position (top-left in the unified
 * desktop, pixels) and whether it's primary. `x`/`y`/`primary` default for back-compat
 * with size-only configs.
 */
export type MonitorSpec = { width: number, height: number, x: number, y: number, primary: boolean, };
