// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-owned lifecycle state. Docker supplies container liveness while passive proxy token
 * activity distinguishes `working` from a running-but-not-working (`idle`) clone.
 */
export type MonitorState = "working" | "idle" | "offline";
