// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-owned lifecycle state. Docker supplies container liveness; `working` versus `idle`
 * answers one question about the clone's agent, "will it get any further without a person",
 * so a clone that has finished, asked something, or wedged all read `idle`.
 */
export type MonitorState = "working" | "idle" | "offline";
