// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One monitor in the global desired layout (sizes only).
 */
export type MonitorSpec = { width: number, height: number, x: number, y: number, primary: boolean, };
