// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVar } from "./EnvVar";

/**
 * A preset as shown to the browser: every field of [`Preset`], Linear key included.
 *
 * The name is a leftover from when this view withheld the key. It withholds nothing now,
 * because the browser queries Linear itself and needs a key to do it, and nothing about the
 * round trip is one-directional either: `merge_presets` stores whatever `linearKey` the
 * editor sends, blank included, so a blank submission CLEARS the stored key. This doc used
 * to claim the opposite — that a blank kept it — which is the more dangerous way to be wrong
 * about a secret, so read `merge_presets`, not this name, for the rule.
 *
 * The same applies to every other field here: a row is rebuilt from the JSON it arrives in
 * and the stored row is not consulted, so a partial row resets what it omits.
 */
export type PresetRedacted = { name: string, labels: Array<string>, 
/**
 * The preset's Linear personal API key, verbatim. Empty when none is configured, which
 * is the whole test the settings panel runs to decide whether its write-only key input
 * reads as already set.
 */
linearKey: string, 
/**
 * Default account pool: a pool name, or `"none"` for any group (rmng picks whichever
 * account is free in any pool) — not secret, shown verbatim.
 */
group: string, 
/**
 * Default fork source: a clone id, or empty for the oldest forkable clone.
 */
defaultForkClone: string, 
/**
 * The preset's environment variables, verbatim. The editor is the only way to set them,
 * so it has to read back what is stored — same reasoning as `linear_key`.
 */
vars: Array<EnvVar>, agentPlaybook: string, globalPrompt: string, startupScript: string, dockerfile: string, };
