// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user message the operator queued for later delivery to a clone's agent.
 *
 * Stored apart from the `Chat` itself (`data/schedules/<id>.json`): a scheduled message
 * is not part of the conversation until it actually fires, at which point it enters the
 * chat as an ordinary `ChatMessage` and disappears from here. Keeping the two files
 * separate means a delivery never has to rewrite the transcript and vice-versa.
 */
export type ScheduledMessage = { id: string, text: string, 
/**
 * When to deliver it, epoch milliseconds (UTC). The UI collects a *local* wall-clock
 * time and converts; the server only ever compares absolute instants, so a client in
 * another timezone (or a DST shift between now and then) can't move the delivery.
 */
at: bigint, 
/**
 * When the operator queued it, epoch milliseconds. Purely informational.
 */
createdAt: bigint, };
