// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSH access settings. The control-server runs a jump-only bastion `sshd`; these keys
 * are installed on the bastion AND every clone. Public keys are NOT secret — the whole
 * struct passes through [`AppConfigRedacted`].
 */
export type SshConfig = { 
/**
 * Whether the bastion runs and keys are provisioned into clones.
 */
enabled: boolean, 
/**
 * Authorized SSH public keys, one full line each (`ssh-ed25519 AAAA… comment`).
 */
authorizedKeys: Array<string>, 
/**
 * Public host/IP the copied command's `-J` jump targets. Empty ⇒ the UI infers it
 * from the address it's already served on. Not secret.
 */
publicHost: string, };
