// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Linear label, with the colour Linear stores for it (`#rrggbb`). The colour is the
 * operator's own scheme over there, so it travels with the label rather than being mapped
 * onto a palette of ours.
 */
export type TicketLabel = { name: string, color: string, };
