// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a Linear issue sits in its workflow: its state *type*, not the workspace's own
 * state name, so `Shipped` and `Done` both arrive here as [`TicketState::Done`].
 *
 * All five are modelled even though the ticket column only ever lists two of them. A
 * sub-issue can be in any state, and drawing a completed one as Todo because the enum could
 * not say otherwise would be worse than carrying three extra variants.
 */
export type TicketState = "backlog" | "todo" | "in_progress" | "done" | "canceled";
