// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketState } from "./TicketState";

/**
 * A pointer to another issue: this one's parent, or one of its sub-issues. Carries only
 * what a one-line row draws, because opening it is a click away in Linear.
 */
export type TicketLink = { 
/**
 * Human identifier, e.g. `WE-143`.
 */
id: string, title: string, url: string, state: TicketState, };
